

import DoctorsCard from "@/components/DoctorsCard";
import Searchbar from "@/components/Searchbar";
export const metadata = {
  title: "Appointment",
  description: "Generated by create next app",
};


const fetchAppointments = async (searchQuery = "") => {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/appoinments?search=${searchQuery}`, {
        cache: 'no-store' 
    });
    const data = await res.json();
    return data || [];
};


const AllAppoinmentsPage = async ({ searchParams }) => {
   
    const search = (await searchParams)?.search || "";
    
    const appointments = await fetchAppointments(search);
    console.log(appointments);

    return (
        <div className="max-w-7xl mx-auto my-10">
           <div className="text-center my-5 space-y-2">
             <h2 className="text-3xl font-bold">All appointments</h2>
             <p className="text-muted">Find the right doctor for you</p>

             
             <Searchbar defaultValue={search} />
           </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
               {
                 appointments.map(appointment => (
                    <DoctorsCard appointment={appointment} key={appointment._id} />
                 ))
               }
            </div>
        </div>
    );
};

export default AllAppoinmentsPage;