

import TabsSection from '@/components/Tabs';
import { auth } from '@/lib/auth';

import { headers } from 'next/headers';
import React from 'react';

import 'react-tabs/style/react-tabs.css';
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashBoardPage =async () => {

     const session = await auth.api.getSession({
    headers: await headers() // you need to pass the headers object.
    
})
const user = session?.user
console.log(user,'from dashboard')

const {token }= await auth.api.getToken({headers: await headers()})
  //  console.log(token ,'from dashborad')

      const res =await fetch(`${process.env.NEXT_PUBLIC_API_URL}/booking/${user?.id}`,{
        headers:{
            authorization: `Bearer ${token}`
        }
    })
       
      const bookingData = await res.json()

      console.log(bookingData)

    return (
        <div className='container mx-auto mt-10'>
          <TabsSection bookingData={bookingData} ></TabsSection>
        </div>
    );
};

export default DashBoardPage;